slam_toolbox:
  ros__parameters:
    solver_plugin: solver_plugins::CeresSolver
    mode: mapping
    
    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    
    # Basic params
    use_map_saver: true
    resolution: 0.05
    max_laser_range: 10.0
    transform_publish_period: 0.02
    map_update_interval: 2.0
    
    # Tuning
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.2
    use_scan_matching: true
    do_loop_closing: true

